workspace:
  base: /go/src
  path: github.com/appleboy/drone-minio

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: golang:1.11
    pull: true
    group: testing
    commands:
      - make vet
      - make lint

  misspell:
    image: golang:1.11
    pull: true
    group: testing
    commands:
      - make misspell-check

  vendor:
    image: golang:1.11
    pull: true
    group: testing
    commands:
      - make test-vendor

  test:
    image: golang:1.11
    pull: true
    group: testing
    commands:
      - make test

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.txt
    when:
      event: [ push, pull_request ]

  build_linux_amd64:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make build_linux_arm

  publish_linux_amd64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]
      local: false

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
